

DO $$ BEGIN IF (CHK_TBL('USER') <= 0) THEN EXECUTE ' CREATE TABLE USER(ID BIGSERIAL NOT NULL)'; END IF; IF (CHK_IX('PK_USER') <= 0) THEN EXECUTE 'CREATE UNIQUE INDEX PK_USER ON USER(ID)'; END IF; END$$;
DO $$ BEGIN IF (CHK_CNSTR('PK_USER') <= 0) THEN EXECUTE 'ALTER TABLE USER ADD CONSTRAINT PK_USER PRIMARY KEY USING INDEX PK_USER'; END IF; END $$;
DO $$ BEGIN IF (CHK_COL('USER','USERNAME') <= 0) THEN EXECUTE 'ALTER TABLE USER ADD USERNAME character varying(20)  NOT NULL'; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('USER','EMAIL') <= 0) THEN EXECUTE 'ALTER TABLE USER ADD EMAIL character varying(100)  NOT NULL'; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('USER','PASSWORD') <= 0) THEN EXECUTE 'ALTER TABLE USER ADD PASSWORD character varying(100) NOT NULL '; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('USER','CREATED_AT') <= 0) THEN EXECUTE 'ALTER TABLE USER ADD CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL '; END IF;END$$;