

DO $$ BEGIN IF (CHK_TBL('MY_FOLDER') <= 0) THEN EXECUTE ' CREATE TABLE MY_FOLDER(ID BIGSERIAL NOT NULL)'; END IF; IF (CHK_IX('PK_FOLDER') <= 0) THEN EXECUTE 'CREATE UNIQUE INDEX PK_FOLDER ON MY_FOLDER(ID)'; END IF; END$$;
DO $$ BEGIN IF (CHK_CNSTR('PK_FOLDER') <= 0) THEN EXECUTE 'ALTER TABLE MY_FOLDER ADD CONSTRAINT PK_FOLDER PRIMARY KEY USING INDEX PK_FOLDER'; END IF; END $$;
DO $$ BEGIN IF (CHK_COL('MY_FOLDER','NAME') <= 0) THEN EXECUTE 'ALTER TABLE MY_FOLDER ADD NAME character varying(100)  NOT NULL'; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('MY_FOLDER','IS_FAVORITE') <= 0) THEN EXECUTE 'ALTER TABLE MY_FOLDER ADD IS_FAVORITE BOOLEAN NOT NULL DEFAULT FALSE'; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('MY_FOLDER','CREATED_AT') <= 0) THEN EXECUTE 'ALTER TABLE MY_FOLDER ADD CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL '; END IF;END$$;