

DO $$ BEGIN IF (CHK_TBL('MY_NOTE') <= 0) THEN EXECUTE ' CREATE TABLE MY_NOTE(ID BIGSERIAL NOT NULL)'; END IF; IF (CHK_IX('PK_NOTE') <= 0) THEN EXECUTE 'CREATE UNIQUE INDEX PK_NOTE ON MY_NOTE(ID)'; END IF; END$$;
DO $$ BEGIN IF (CHK_CNSTR('PK_NOTE') <= 0) THEN EXECUTE 'ALTER TABLE MY_NOTE ADD CONSTRAINT PK_NOTE PRIMARY KEY USING INDEX PK_NOTE'; END IF; END $$;
DO $$ BEGIN IF (CHK_COL('MY_NOTE','USER_ID') <= 0) THEN EXECUTE 'ALTER TABLE MY_NOTE ADD USER_ID numeric(10);'; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('MY_NOTE','FOLDER_ID') <= 0) THEN EXECUTE 'ALTER TABLE MY_NOTE ADD FOLDER_ID numeric(10);'; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('MY_NOTE','TITLE') <= 0) THEN EXECUTE 'ALTER TABLE MY_NOTE ADD TITLE character varying(100)'; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('MY_NOTE','CONTENT') <= 0) THEN EXECUTE 'ALTER TABLE MY_NOTE ADD CONTENT character varying(2000)'; END IF;END$$;

DO $$ BEGIN IF (CHK_COL('MY_NOTE','IS_FAVORITE') <= 0) THEN EXECUTE 'ALTER TABLE MY_NOTE ADD IS_FAVORITE BOOLEAN NOT NULL DEFAULT FALSE'; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('MY_NOTE','CREATED_AT') <= 0) THEN EXECUTE 'ALTER TABLE MY_NOTE ADD CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL '; END IF;END$$;
DO $$ BEGIN IF (CHK_COL('MY_NOTE','UPDATED_AT') <= 0) THEN EXECUTE 'ALTER TABLE MY_NOTE ADD UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL '; END IF;END$$;